### ISSUE TITLE
Generate Enum

### ISSUE THREAD

**Issue by JohanKustner** [gerasimovroman/crm.webApi.earlyBoundGenerator#3]
The CrmSvcUtil.exe allowed an extension, in order to generate enum for option sets, status and status reason. Can this be added to the tool?

**Comment by gerasimovroman** [comment]
Hi, yes. I added this feature, but have not yet published in XrmToolbox store, will publish soon

**Comment by JohanKustner** [comment]
I see that the feature is there now. Thanks for adding it. One things I noticed is that the names contain underscores, which violates Microsoft Naming Guidelines and introduces a whole lot of Code Analysis Warnings.

Can you follow [https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines](url) when naming your classes/fields/methods/properties/etc. please?

Code Analysis Warnings are generated when the Microsoft Naming Guidelines are violated.

One thing I've noticed in your naming is the use of underscores for public types (private is fine - but you should follow Roslyn and/or Resharper recommended naming).
